<?php
$history = "History";
$characters = "Characters";
$login = "Log In";
$register = "Register";
$developers = "Developers";
$user = "User";
$passwd = "Password";
$passwd2 = "Confirm password";
$indexTitle1 = "Who are we?";
$indexText1 = "We are a team which iniciate a project to create and developed a videogame following the SCRUM methology.
Everything came up because three CES Lope de VEGA´s classmate from Cordoba decided to set up a videogame according to their own belong.
They collected some ideas from other games, series and films from other producers of this genre, to improve and adapt the original stories of their videogame to do it more attractive to the fans.
";
$indexTitle2 = "Our aim";
$indexText2 = "Our goal is set up a videogame which can be enjoyed by everybody and can be adapted to the personality´s gamer. I could be more conservative or riskier during the course of his adventure through the Kingdom of Edelaiah.";
$indexContacto = "Be in contact with us if you have any question or suggestion";
$historyTextP1 = "For centuries, orcs were enslaved by humans and elves due to their strength, ability not to get sick, and their resistant. They were treated as the worst thing and were given with the toughest jobs, such as walls construction. In this places, they had to work next to the corpses of their colleagues, dead due to the work-related fatigue. Rebellion was soon carried out when Urrek, an orc with an intelligence above the average, decided that it was time to end the orcs repression which it had plagued them since the day of their birth. Amazingly enough, orcs took control of big cities by surprise in a brutal, indiscriminate and implacable way. Astonished, humans and elves did not know how to react. After these events, Urrek did not take long to become obsessed with the Orb of Hael so he decided the siege of Dalingas.";
$historyTextP2 = "Valiant was child in the city of Dalingas who was born in the core of an extremely troubled suburb. He was training tirelessly to become a Protector of Ithril, one of the most important positions in the city. Those protectors cared for the Orb of Hael, one of the most powerful artifacts conceived in the Kingdom of Edelaiah. After the orcs invasion of this city, Urrek, the leader of the assault, betraying the will of his comrades, he took the power of the Orb and subjected them. During the invasion, the town was razed to the ground, leaving a few survivors who managed to escape before the orcs enter to city through the walls. 
In the siege, Valiant's mother was mercilessly executed by Urrek, under the desperate watchful eye of her son. After escaping from him, Valiant swore to himself that he would fight against orcs until his last breath. In this way, he triggered of the beginning of his adventure to the quest for revenge and the conquest of ancient Dalingas, nowadays known as Ogkrum ... 
";
$historyTextP3 = "In a world almost conquered by the orcs, the last resistance of elves and humans joined forces to combat againts those who constantly attacked its last strongholds, such as the city of Xitra, the last city of elves and humans. This one, located inside a cave, was especially difficult to attack because the only entrance to the city was guarded by a Xare dragon, one of the most intelligent races of dragons. It was specifically trained to attack orcs when it was given with a signal. The Orb could not dominate this dragón due to its intelligence so Urrek decided not to attack this city for the moment. ";
$charactersTextValiant = "Valiant: A young man who was determined to succeed in his life. His dream was frustrated by the invasion of his native city, Dalingas, at the hands of an army of orcs when he was still a child. Powerless at seeing his mother to be executed by the orc who led the assault, he swore revenge and death to everyone who get in his way. ";
$charactersTextGladios = "Gladios: One of the mercenaries most feared by the orcs, not only because he was dedicated to hunting them but because he was a lethal and ruthless assassin. Due to his skill and his need for money, he was turned  into a bloodthirsty mercenary, who was hired by some humans to 'settle' their debts with some orcs.";
$charactersTextTaely = "Taely: An elven witch who participated in the ancient war. Due to her participation in the war, she considered creating an enchantment which would allow her not to age, an, not to die due to natural causes. She managed to find the key to create the enchantment but after using it on herself she forgot the essence of the enchantment due to the temporary fatigue that it caused her. Due to these events, she became cautious and mistrustful. ";
$charactersTextKrulom = "Krulom: An extremely intelligent orc defector from his race. After participating in the assault on Dalingas, he realized Urrek's true intentions, so he fled before Urrek took the Orb control and not to succumb to him.";
$charactersTextUrrek = "Urrek: An orc who stood out above the rest of members of his specie for his twisted brilliant mind. For this reason he was rejected by the others, but, as time passed, he began to know how to control weaker-minded orcs with just words. However, he noticed that some others did not succumb to his charms so he became obsessed with the Orb of Hael. This obsession caused him to incite the other orcs to a rebellion against the elves and humans.";
$charactersTextTroug = "Troug: 'A very beastly big man, short of intelligence', at least that's how the other orcs define him. He was simply raised to be a war beast, Nobody never made an effort to give him an education, even though he demonstrated an excellent learning ability. His education simply focused on the SDK rule 'Smash, destroy, kill'. Those are the only words that this beast knows how to pronounce correctly.";
$charactersTextRegrug = "Regrug: An orc who is the opposite of big and strong. Due to his size and weakness, everyone thought he would never stand out, but against all odds he managed to be chosen as one of Ogkrum's defending commanders. He achieved it thanks to his cheating, cowardly and manipulative behaviour. He is able to flee from you leading you to a death trap where you will enjoy a pyrotechnics show in the first person.";
?>
